CORE-3643 Replace dockerised checkov action with uv tool
We were encountering several issues with the use of the dockerised action when running checkov on persistent self-hosted runners.

In particular, there seems to be an issue with between how the work directory is mounted between the host, the runner container and the action container and how the checkov container action registers problem matchers:

```
Error: Unable to process command '::add-matcher::checkov-problem-matcher.json' successfully.
Error: Could not find file '/home/runner/actions-runner/_work/cdp-tf-svc-bedrock/cdp-tf-svc-bedrock/checkov-problem-matcher.json'.
```

Troubleshooting attempts were ultimately fruitless. As this appears to be the only issue we're having with the docker-out-of-docker pattern, it felt more pragmatic to workaround the issue with a drop in uv tool replacement instead of implementing a more convoluted workaround.