CORE-3643 Remove GitHub credential persistance and git config changes
Attempt to fix intermittent problems with downloading modules on persistent GitHub runners. Hypothesis is that this is caused by expired credentials, which this attempts to avoid:

```
  Error: Terraform exited with code 1.
  │ Error: Failed to download module
  │
  │   on main.tf line 2:
  │    2: module "tenant_config" {
  │
  │ Could not download module "tenant_config" (main.tf:2) source code from
  │ "git::https://github.com/DEFRA/cdp-tenant-config.git": error downloading
  │ 'https://github.com/DEFRA/cdp-tenant-config.git': /usr/bin/git exited with
  │ 128: Cloning into '.terraform/modules/tenant_config'...
  │ remote: Invalid username or token. Password authentication is not supported
  │ for Git operations.
  │ fatal: Authentication failed for
  │ 'https://github.com/DEFRA/cdp-tenant-config.git/'
```